// src/components/Auth.vue
<template>
  <nav class="flex gap-2 text-red-700">
    <DeleteAccount v-if="local && currentUser" :current-user="currentUser"/>
    <SignOut v-if="currentUser" />
    <SignInWithTestEmailPassword v-else-if="dev" />
    <SignInWithGoogle v-else />
  </nav>
</template>

<script setup>
import { toRefs } from 'vue';
import SignInWithGoogle from './SignInWithGoogle.vue';
import SignInWithTestEmailPassword from './SignInWithTestEmailPassword.vue';
import SignOut from './SignOut.vue';
import DeleteAccount from './DeleteAccount.vue';

const dev = process.env.PROJECT_ID !== 'records-classificater';
const local = process.env.NODE_ENV !== 'production';

const props = defineProps({
  currentUser: { default: null },
});

const { currentUser } = toRefs(props);
</script>

// src/components/Auth.jsx
import SignInWithGoogle from './SignInWithGoogle';
import SignInWithTestEmailPassword from './SignInWithTestEmailPassword';
import SignOut from './SignOut';
import DeleteAccount from './DeleteAccount';

const dev = process.env.PROJECT_ID !== 'records-classificater';
const local = process.env.NODE_ENV !== 'production';

export default function Auth({ currentUser = null }) {
  return (
    <nav className="flex gap-2 text-red-700">
      {local && currentUser && <DeleteAccount currentUser={currentUser} />}
      {currentUser ? (
        <SignOut />
      ) : dev ? (
        <SignInWithTestEmailPassword />
      ) : (
        <SignInWithGoogle />
      )}
    </nav>
  );
}
