// src/sections/TripClassificater.tsx
import type { User } from 'firebase/auth';
import { getFirestore, onSnapshot, doc, addDoc, query, writeBatch, getDoc, where, updateDoc, Timestamp, type Unsubscribe } from 'firebase/firestore';
import { useEffect, useMemo, useRef, useState } from 'react';
import NewTrip from './components/NewTrip';
import { channelCollection, channelDoc } from '../firestore/channel';
import { tripConverter, type Trip } from '../firestore/definitions/Trip';
import { userConverter } from '../firestore/definitions/User';
import { tripsConverter } from '../firestore/definitions/Trips';
import { Vehicle, vehicleConverter } from '../firestore/definitions/Vehicle';
import Loader from '../components/Loader';

interface TripIdentified extends Trip {
  id: string,
}

interface TripCalculated extends TripIdentified {
  trip: number,
}

interface VehicleIdentified extends Vehicle {
  id: string,
}

// 分類ごとに色を割り当て、業務用と私用を一目で見分けられるようにする
const classPalette = [
  'bg-blue-100 text-blue-800',
  'bg-amber-100 text-amber-800',
  'bg-emerald-100 text-emerald-800',
  'bg-rose-100 text-rose-800',
  'bg-violet-100 text-violet-800',
  'bg-cyan-100 text-cyan-800',
];

function sortByTimestamp({ timestamp: t1 }: Trip, { timestamp: t2 }: Trip) {
  return (t1 as unknown as number) - (t2 as unknown as number);
}

function formatDate(timestamp: Timestamp) {
  const d = timestamp.toDate();
  return `${d.getFullYear()}年${d.getMonth() + 1}月${d.getDate()}日 ${d.getHours().toString().padStart(2, '0')}:${d.getMinutes().toString().padStart(2, '0')}`;
}

function formatNumber(number: number) {
  return number.toFixed(6).replace(/\.?0*$/, '');
}

// 実機では、購読が「初回スナップショットもエラーも返さないまま止まる」ことが
// ある（一時的な通信断や、ネイティブダイアログ表示の前後など）。リロードでしか
// 復帰しないのを避けるため、初回が届かなければ購読を張り直す。
const FIRST_SNAPSHOT_TIMEOUT_MS = 5000;
const MAX_SUBSCRIBE_ATTEMPTS = 3;

/**
 * onSnapshot を張り直しつきで購読する。初回スナップショットが時間内に届かない
 * か、エラーになった場合は購読を張り直し、上限まで駄目なら onGiveUp を呼ぶ。
 *
 * `subscribe` は「毎回まっさらな状態から購読する」ように書くこと。張り直すと
 * 最初のスナップショットで全件が改めて届くため、積み上げ式に持つ状態は
 * subscribe の中で捨てる必要がある。
 */
function subscribeWithRetry(
  subscribe: (onFirstSnapshot: () => void, onError: () => void) => Unsubscribe,
  onGiveUp: () => void,
): Unsubscribe {
  let attempts = 0;
  let generation = 0;
  let unsubscribe: Unsubscribe | null = null;
  let timer: ReturnType<typeof setTimeout> | undefined;
  let stopped = false;

  function clearTimer() {
    if (timer !== undefined) clearTimeout(timer);
    timer = undefined;
  }

  function start() {
    const gen = generation += 1;
    attempts += 1;
    let received = false;
    // 見張りを先に仕掛ける。世代を見ているので、張り直したあとに古い見張りが
    // 起きても何もしない
    timer = setTimeout(() => {
      if (!received && gen === generation) restart();
    }, FIRST_SNAPSHOT_TIMEOUT_MS);
    const unsub = subscribe(() => {
      received = true;
      if (gen === generation) clearTimer();
    }, () => {
      if (gen === generation) restart();
    });
    // subscribe がその場でエラーを返した場合は既に次の世代へ進んでいるため、
    // ここで取り違えないようにする
    if (gen === generation) unsubscribe = unsub;
    else unsub();
  }

  function restart() {
    clearTimer();
    unsubscribe?.();
    unsubscribe = null;
    if (stopped) return;
    if (attempts >= MAX_SUBSCRIBE_ATTEMPTS) {
      onGiveUp();
      return;
    }
    start();
  }

  start();
  return () => {
    stopped = true;
    clearTimer();
    unsubscribe?.();
    unsubscribe = null;
  };
}

export default function TripClassificater({ currentUser }: { currentUser: User }) {
  // initializeApp 後に評価されるよう、Firestore はコンポーネント内で取得する
  const db = getFirestore();
  const [currentVehicleId, setCurrentVehicleId] = useState<string | null>(null);
  const [vehicleClasses, setVehicleClasses] = useState<string[]>([]);
  const [currentYear, setCurrentYear] = useState(() => (new Date()).getFullYear());
  const [vehicles, setVehicles] = useState<VehicleIdentified[]>([]);
  const [trips, setTrips] = useState<TripIdentified[]>([]);
  const [newTripEnabled, setNewTripEnabled] = useState(false);
  // 取得前の空データを「記録なし」と誤表示しないよう、読み込み完了を明示的に管理する
  const [userLoaded, setUserLoaded] = useState(false);
  const [vehiclesLoaded, setVehiclesLoaded] = useState(false);
  const [tripsLoaded, setTripsLoaded] = useState(false);
  const [loadError, setLoadError] = useState('');
  // 移行処理の実行中フラグ。移行中に届くスナップショットは自分のローカル書き込みの
  // 反映であり、参照先の車両がまだサーバーに無いため状態へ反映してはいけない
  const migrating = useRef(false);

  useEffect(() => {
    setVehicles([]);
    setUserLoaded(false);
    setVehiclesLoaded(false);
    setLoadError('');
    migrating.current = false;
    const unsubUser = subscribeWithRetry((onFirstSnapshot, onError) => onSnapshot(channelDoc(db, 'users', currentUser.uid).withConverter(userConverter), async (snapshot) => {
      onFirstSnapshot();
      if (!snapshot.exists()) {
        // 旧データからの移行（初回登録を含む）
        if (migrating.current) return;
        migrating.current = true;
        try {
          const { data: oldTrips } = (await getDoc(channelDoc(db, 'trips', currentUser.uid).withConverter(tripsConverter))).data() || { data: [] };
          const classes = Array.from(oldTrips.reduce((acc, { class: cls }) => {
            return acc.add(cls);
          }, new Set<string>()));
          const name = prompt('車の名称を入力してください');
          const batch1 = writeBatch(db);
          const newVehicle = doc(channelCollection(db, 'vehicles')).withConverter(vehicleConverter);
          await batch1
            .set(newVehicle, {
              classes,
              name: name || '',
              permissions: {
                read: [currentUser.uid],
                write: [currentUser.uid],
              },
            })
            .set(channelDoc(db, 'users', currentUser.uid).withConverter(userConverter), {
              state: { vehicle: newVehicle.id },
            })
            .commit();
          const batch2 = writeBatch(db);
          oldTrips.forEach((trip) => {
            batch2.set(doc(channelCollection(db, 'vehicles', newVehicle.id, 'trips')).withConverter(tripConverter), trip);
          });
          // 過去記録の移行に失敗しても車両自体は作成済みなので、画面は進める
          await batch2.commit().catch(() => setLoadError('過去の記録の移行に失敗しました'));
          // commit の解決はサーバー確定を待つ。trips のルールは親の車両ドキュメントを
          // get して権限を見るため、サーバーに車両が無いうちに購読を始めると
          // 権限エラーでリスナーが終了してしまう。確定後にまとめて反映する
          setCurrentVehicleId(newVehicle.id);
          setUserLoaded(true);
        } catch {
          // 失敗時もローダーを解除し、画面が固まらないようにする
          setLoadError('データの読み込みに失敗しました');
          setUserLoaded(true);
        } finally {
          migrating.current = false;
        }
        return;
      }
      if (migrating.current) return;
      setCurrentVehicleId(snapshot.data().state.vehicle);
      setUserLoaded(true);
    }, onError), () => {
      setLoadError('データの読み込みに失敗しました');
      setUserLoaded(true);
    });
    const unsubVehicles = subscribeWithRetry((onFirstSnapshot, onError) => {
      // 張り直すと全件が改めて 'added' で届くため、積み上げた一覧は捨てる
      setVehicles([]);
      return onSnapshot(query(channelCollection(db, 'vehicles'), where('permissions.read', 'array-contains', currentUser.uid)).withConverter(vehicleConverter), (snapshot) => {
        // 1 件の変換に失敗しても読み込み中のまま止まらないよう、完了を先に記録する
        onFirstSnapshot();
        setVehiclesLoaded(true);
        snapshot.docChanges().forEach(({ doc, type }) => {
          setVehicles((prev) => {
            if (type === 'added') {
              return [...prev, { ...doc.data(), id: doc.id }];
            }
            const i = prev.findIndex(({ id }) => doc.id === id);
            if (i < 0) return prev;
            if (type === 'modified') {
              const next = [...prev];
              next[i] = { ...doc.data(), id: doc.id };
              return next;
            }
            return prev.filter((_, idx) => idx !== i);
          });
        });
      }, onError);
    }, () => {
      setLoadError('車両一覧の読み込みに失敗しました');
      setVehiclesLoaded(true);
    });
    return () => {
      unsubUser();
      unsubVehicles();
    };
  }, [currentUser]);

  useEffect(() => {
    // 車両切り替え時は前の車両の記録を残さず、読み込み中として扱う
    setTrips([]);
    setVehicleClasses([]);
    setTripsLoaded(false);
    if (!currentVehicleId) return;
    const unsubVehicle = subscribeWithRetry((onFirstSnapshot, onError) => onSnapshot(channelDoc(db, 'vehicles', currentVehicleId).withConverter(vehicleConverter), (snapshot) => {
      onFirstSnapshot();
      setVehicleClasses(snapshot.data()?.classes || []);
    }, onError), () => {
      setVehicleClasses([]);
    });
    const unsubTrips = subscribeWithRetry((onFirstSnapshot, onError) => {
      // 張り直すと全件が改めて 'added' で届くため、積み上げた一覧は捨てる
      setTrips([]);
      return onSnapshot(channelCollection(db, 'vehicles', currentVehicleId, 'trips').withConverter(tripConverter), (snapshot) => {
        // 1 件の変換に失敗しても読み込み中のまま止まらないよう、完了を先に記録する
        onFirstSnapshot();
        setTripsLoaded(true);
        snapshot.docChanges().forEach(({ type, doc }) => {
          setTrips((prev) => {
            if (type === 'added') {
              return [...prev, { ...doc.data(), id: doc.id }];
            }
            const i = prev.findIndex(({ id }) => id === doc.id);
            if (i < 0) return prev;
            if (type === 'modified') {
              const next = [...prev];
              next[i] = { ...doc.data(), id: doc.id };
              return next;
            }
            return prev.filter((_, idx) => idx !== i);
          });
        });
      }, onError);
    }, () => {
      setLoadError('走行記録の読み込みに失敗しました');
      setTripsLoaded(true);
    });
    return () => {
      unsubVehicle();
      unsubTrips();
    };
  }, [currentVehicleId]);

  const calculatedTrips = useMemo<TripCalculated[]>(() => {
    const [first, ...remains] = [...trips].sort(sortByTimestamp);
    if (!first) return [];
    return remains.reduce(([acc, odo]: [TripCalculated[], number], trip: TripIdentified): [TripCalculated[], number] => {
      acc.push({ ...trip, trip: trip.odo - odo });
      return [acc, trip.odo];
    }, [[{ ...first, trip: 0 }], first.odo] as [TripCalculated[], number])[0];
  }, [trips]);

  const classSummaries = useMemo(() => calculatedTrips.filter(({ timestamp }) => {
    return timestamp.toDate().getFullYear() === currentYear;
  }).reduce((acc, { class: c, trip }) => {
    if (!(c in acc)) acc[c] = 0;
    if (trip !== undefined) acc[c] += trip;
    return acc;
  }, {} as Record<string, number>), [calculatedTrips, currentYear]);

  const sum = useMemo(() => {
    const last = [...calculatedTrips].reverse().find(({ timestamp }) => timestamp.toDate().getFullYear() === currentYear);
    let first = [...calculatedTrips].reverse().find(({ timestamp }) => timestamp.toDate().getFullYear() === currentYear - 1);
    if (!first) first = calculatedTrips.find(({ timestamp }) => timestamp.toDate().getFullYear() === currentYear);
    if (!first || !last) return 0;
    return last.odo - first.odo;
  }, [calculatedTrips, currentYear]);

  // 一覧は新しい順に表示する（trip の差分計算は古い順のまま）
  const displayTrips = useMemo(() => [...calculatedTrips].reverse(), [calculatedTrips]);

  // trips はスナップショット順で時系列とは限らないため、ODO（単調増加）の最大値を最新値とする
  const lastODO = useMemo(() => trips.reduce((max, { odo }) => (odo > max ? odo : max), 0), [trips]);

  // ユーザー情報と車両一覧が揃うまでは選択肢を確定できない
  const vehiclesLoading = !userLoaded || !vehiclesLoaded;
  // 車両が決まる前や切り替え直後は、記録が空でも「記録なし」とは判断しない
  const tripsLoading = !userLoaded || (!!currentVehicleId && !tripsLoaded);

  function classStyle(cls: string) {
    const i = vehicleClasses.indexOf(cls);
    return classPalette[(i < 0 ? 0 : i) % classPalette.length];
  }

  function setCurrentVehicle(event: React.ChangeEvent<HTMLSelectElement>) {
    updateDoc(channelDoc(db, 'users', currentUser.uid), {
      'state.vehicle': event.target.value,
    });
  }

  // 却下時は理由を返し、フォーム側でユーザーに提示できるようにする
  function createTrip(trip: Trip): string | null {
    const prevTrip = [...calculatedTrips].reverse().find(({ timestamp }) => trip.timestamp.seconds > timestamp.seconds || trip.timestamp.seconds === timestamp.seconds && trip.timestamp.nanoseconds > timestamp.nanoseconds);
    const nextTrip = calculatedTrips.find(({ timestamp }) => trip.timestamp.seconds < timestamp.seconds || trip.timestamp.seconds === timestamp.seconds && trip.timestamp.nanoseconds < timestamp.nanoseconds);
    if (prevTrip && trip.odo <= prevTrip.odo) return `ODOは前の記録（${formatNumber(prevTrip.odo)} km）より大きい値を入力してください`;
    if (nextTrip && trip.odo >= nextTrip.odo) return `ODOは次の記録（${formatNumber(nextTrip.odo)} km）より小さい値を入力してください`;
    if (!currentVehicleId) return '車両が選択されていません';
    addDoc(channelCollection(db, 'vehicles', currentVehicleId, 'trips').withConverter(tripConverter), trip);
    setNewTripEnabled(false);
    return null;
  }

  return (
    <>
      {/* 車両切り替え（利用頻度が高いので常に上部に固定） */}
      <section className="sticky top-0 z-20 -mx-4 px-4 py-3 bg-white/95 backdrop-blur border-b border-gray-200 flex items-center gap-3">
        <label className="flex items-center gap-2 grow min-w-0">
          <span className="text-sm font-medium text-gray-500 shrink-0">車両</span>
          <select
            onChange={setCurrentVehicle}
            value={currentVehicleId ?? ''}
            disabled={vehiclesLoading}
            className="grow min-w-0 text-lg font-medium py-2 px-3 rounded-lg border border-gray-300 bg-white focus:outline-none focus:border-lime-500 disabled:text-gray-400"
          >
            {/* 選択中の車両が一覧に現れるまでは、空表示ではなく状態を示す選択肢を出す */}
            {!vehicles.some(({ id }) => id === currentVehicleId) && (
              <option value={currentVehicleId ?? ''}>{vehiclesLoading ? '読み込み中…' : '車両がありません'}</option>
            )}
            {vehicles.map(({ id, name }) => (
              <option key={id} value={id}>{name}</option>
            ))}
          </select>
        </label>
      </section>

      {loadError && <p className="mt-3 text-sm text-red-600 text-center" role="alert">{loadError}</p>}

      {/* 年間集計（確認頻度は低いので折りたたみ） */}
      <details className="my-3 rounded-xl border border-gray-200 bg-gray-50 overflow-hidden">
        <summary className="cursor-pointer select-none px-4 py-3 font-bold text-gray-700 flex items-center gap-2">
          <span className="text-lime-600">📊</span>
          {currentYear}年の集計
        </summary>
        <div className="px-4 pb-4 space-y-3">
          <div className="flex items-center justify-center gap-4">
            <button className="w-9 h-9 rounded-full border border-gray-300 text-gray-600 active:bg-gray-200" onClick={() => setCurrentYear((y) => y - 1)}>‹</button>
            <span className="font-black text-lg tabular-nums">{currentYear}</span>
            <button className="w-9 h-9 rounded-full border border-gray-300 text-gray-600 active:bg-gray-200" onClick={() => setCurrentYear((y) => y + 1)}>›</button>
          </div>
          {tripsLoading ? (
            <Loader className="text-lime-500 text-2xl py-2" />
          ) : Object.keys(classSummaries).length ? (
            <dl className="space-y-2">
              {Object.entries(classSummaries).map(([key, value]) => (
                <div key={key} className="flex items-center gap-3">
                  <dt className={`${classStyle(key)} shrink-0 text-xs font-medium px-2 py-1 rounded-full`}>{key}</dt>
                  <dd className="grow text-right tabular-nums font-medium">{formatNumber(value)} km</dd>
                  {sum ? <dd className="w-16 text-right text-sm text-gray-500 tabular-nums">{Math.round(value / sum * 1000) / 10} %</dd> : null}
                </div>
              ))}
            </dl>
          ) : (
            <p className="text-center text-sm text-gray-400 py-2">記録がありません</p>
          )}
        </div>
      </details>

      {/* 走行記録一覧（新しい順） */}
      <ul className="space-y-3 pb-28">
        {displayTrips.map(({ id, timestamp, odo, trip, class: cls }) => (
          <li
            key={id}
            className="rounded-xl border border-gray-200 bg-white shadow-sm p-4"
          >
            <div className="flex items-center justify-between gap-2">
              <span className="text-sm text-gray-500 tabular-nums">{formatDate(timestamp)}</span>
              <span className={`${classStyle(cls)} text-xs font-medium px-2.5 py-1 rounded-full`}>{cls}</span>
            </div>
            <div className="mt-3 flex items-end justify-between gap-4">
              {trip ? (
                <div className="flex flex-col">
                  <span className="text-xs text-gray-400">走行 (TRIP)</span>
                  <span className="text-2xl font-bold tabular-nums text-gray-800">{formatNumber(trip)}<span className="text-sm font-normal text-gray-500 ml-1">km</span></span>
                </div>
              ) : null}
              <div className="flex flex-col items-end ml-auto">
                <span className="text-xs text-gray-400">総距離 (ODO)</span>
                <span className="text-lg font-medium tabular-nums text-gray-600">{formatNumber(odo)}<span className="text-sm font-normal text-gray-400 ml-1">km</span></span>
              </div>
            </div>
          </li>
        ))}
        {tripsLoading ? (
          <li className="py-10">
            <Loader className="text-lime-500 text-3xl" />
          </li>
        ) : !displayTrips.length ? (
          <li className="text-center text-gray-400 py-10">
            {currentVehicleId ? (
              <>まだ記録がありません。<br />下のボタンから追加できます。</>
            ) : '車両が選択されていません。'}
          </li>
        ) : null}
      </ul>

      {/* 記録追加（主要操作なので画面下端に固定バーで常時表示） */}
      {currentVehicleId && !newTripEnabled && (
        <div
          className="fixed inset-x-0 bottom-0 z-30 bg-white/80 backdrop-blur border-t border-gray-200 px-4 pt-4"
          style={{ paddingBottom: 'calc(0.5rem + env(safe-area-inset-bottom))' }}
        >
          <button
            onClick={() => setNewTripEnabled(true)}
            className="w-full bg-lime-500 text-white rounded-xl py-3 font-bold text-lg shadow active:bg-lime-600 flex items-center justify-center gap-2"
          >
            <span className="text-2xl font-light leading-none">＋</span> 走行を記録
          </button>
        </div>
      )}

      {/* 入力フォーム（画面上端に固定し、キーボードに隠れないようにする） */}
      {newTripEnabled && (
        <div
          className="fixed inset-0 z-40 flex items-start bg-black/40"
          onClick={(e) => { if (e.target === e.currentTarget) setNewTripEnabled(false); }}
        >
          <div className="w-full bg-white rounded-b-2xl px-5 pb-4 max-h-full overflow-y-auto shadow-2xl" style={{ paddingTop: 'calc(0.5rem + env(safe-area-inset-top))' }}>
            <NewTrip minOdo={lastODO} onSubmit={createTrip} onCancel={() => setNewTripEnabled(false)} classOptions={vehicleClasses} />
          </div>
        </div>
      )}
    </>
  );
}

// src/sections/TripClassificater.vue
<template>
  <!-- 車両切り替え（利用頻度が高いので常に上部に固定） -->
  <section class="sticky top-0 z-20 -mx-4 px-4 py-3 bg-white/95 backdrop-blur border-b border-gray-200 flex items-center gap-3">
    <label class="flex items-center gap-2 grow min-w-0">
      <span class="text-sm font-medium text-gray-500 shrink-0">車両</span>
      <select
        @change="setCurrentVehicle"
        :value="currentVehicleId"
        class="grow min-w-0 text-lg font-medium py-2 px-3 rounded-lg border border-gray-300 bg-white focus:outline-none focus:border-lime-500"
      >
        <option v-for="{ id, name } in vehicles" :key="id" :value="id">{{ name }}</option>
      </select>
    </label>
    <button class="shrink-0 text-sm text-blue-700 py-2 px-2" @click="share">
      共有
    </button>
  </section>

  <!-- 年間集計（確認頻度は低いので折りたたみ） -->
  <details class="my-3 rounded-xl border border-gray-200 bg-gray-50 overflow-hidden">
    <summary class="cursor-pointer select-none px-4 py-3 font-bold text-gray-700 flex items-center gap-2">
      <span class="text-lime-600">📊</span>
      {{ currentYear }}年の集計
    </summary>
    <div class="px-4 pb-4 space-y-3">
      <div class="flex items-center justify-center gap-4">
        <button class="w-9 h-9 rounded-full border border-gray-300 text-gray-600 active:bg-gray-200" @click="currentYear -= 1">‹</button>
        <span class="font-black text-lg tabular-nums">{{ currentYear }}</span>
        <button class="w-9 h-9 rounded-full border border-gray-300 text-gray-600 active:bg-gray-200" @click="currentYear += 1">›</button>
      </div>
      <dl v-if="Object.keys(classSummaries).length" class="space-y-2">
        <div v-for="(value, key) in classSummaries" :key="key" class="flex items-center gap-3">
          <dt :class="classStyle(key)" class="shrink-0 text-xs font-medium px-2 py-1 rounded-full">{{ key }}</dt>
          <dd class="grow text-right tabular-nums font-medium">{{ formatNumber(value) }} km</dd>
          <dd class="w-16 text-right text-sm text-gray-500 tabular-nums" v-if="sum">{{ Math.round(value / sum * 1000) / 10 }} %</dd>
        </div>
      </dl>
      <p v-else class="text-center text-sm text-gray-400 py-2">記録がありません</p>
    </div>
  </details>

  <!-- 走行記録一覧（新しい順） -->
  <ul class="space-y-3 pb-28">
    <li
      v-for="{ id, timestamp, odo, trip, class: cls } in displayTrips"
      :key="id"
      class="rounded-xl border border-gray-200 bg-white shadow-sm p-4"
    >
      <div class="flex items-center justify-between gap-2">
        <span class="text-sm text-gray-500 tabular-nums">{{ formatDate(timestamp) }}</span>
        <span :class="classStyle(cls)" class="text-xs font-medium px-2.5 py-1 rounded-full">{{ cls }}</span>
      </div>
      <div class="mt-3 flex items-end justify-between gap-4">
        <div v-if="trip" class="flex flex-col">
          <span class="text-xs text-gray-400">走行 (TRIP)</span>
          <span class="text-2xl font-bold tabular-nums text-gray-800">{{ formatNumber(trip) }}<span class="text-sm font-normal text-gray-500 ml-1">km</span></span>
        </div>
        <div class="flex flex-col items-end ml-auto">
          <span class="text-xs text-gray-400">総距離 (ODO)</span>
          <span class="text-lg font-medium tabular-nums text-gray-600">{{ formatNumber(odo) }}<span class="text-sm font-normal text-gray-400 ml-1">km</span></span>
        </div>
      </div>
    </li>
    <li v-if="!displayTrips.length" class="text-center text-gray-400 py-10">
      まだ記録がありません。<br />下のボタンから追加できます。
    </li>
  </ul>

  <!-- 記録追加（主要操作なので画面下端に固定バーで常時表示） -->
  <div
    v-if="currentVehicleId && !newTripEnabled"
    class="fixed inset-x-0 bottom-0 z-30 bg-white/80 backdrop-blur border-t border-gray-200 px-4 pt-4"
    style="padding-bottom: calc(0.5rem + env(safe-area-inset-bottom))"
  >
    <button
      @click="newTripEnabled = true"
      class="w-full bg-lime-500 text-white rounded-xl py-3 font-bold text-lg shadow active:bg-lime-600 flex items-center justify-center gap-2"
    >
      <span class="text-2xl font-light leading-none">＋</span> 走行を記録
    </button>
  </div>

  <!-- 入力フォーム（画面上端に固定し、キーボードに隠れないようにする） -->
  <div
    v-if="newTripEnabled"
    class="fixed inset-0 z-40 flex items-start bg-black/40"
    @click.self="newTripEnabled = false"
  >
    <div class="w-full bg-white rounded-b-2xl px-5 pb-4 max-h-full overflow-y-auto shadow-2xl" style="padding-top: calc(0.5rem + env(safe-area-inset-top))">
      <NewTrip :min-odo="lastODO" @submit="createTrip" @cancel="newTripEnabled = false" :classOptions="vehicleClasses" />
    </div>
  </div>
</template>

<script setup lang="ts">
import type { User } from 'firebase/auth';
import { getFirestore, onSnapshot, doc, addDoc, setDoc, query, collection, writeBatch, getDoc, Unsubscribe, where, updateDoc, arrayUnion } from 'firebase/firestore';
import type { Ref } from 'vue';
import { toRefs, watch, ref, computed } from 'vue';
import NewTrip from './components/NewTrip.vue';
import { tripConverter, type Trip } from '../firestore/definitions/Trip';
import { userConverter } from '../firestore/definitions/User';
import { tripsConverter } from '../firestore/definitions/Trips';
import { Vehicle, vehicleConverter } from '../firestore/definitions/Vehicle';

const props = defineProps<{
  currentUser: User,
}>();

const { currentUser } = toRefs(props);
const currentVehicleId: Ref<string|null> = ref(null);
const vehicleClasses: Ref<string[]> = ref([]);

const currentYear = ref((new Date()).getFullYear());

interface TripIdentified extends Trip {
  id: string,
}

interface TripCalculated extends TripIdentified {
  trip: number,
}

interface VehicleIdentified extends Vehicle {
  id: string,
}

const vehicles: Ref<VehicleIdentified[]> = ref([]);

function setCurrentVehicle(event) {
  updateDoc(doc(db, 'users', currentUser.value.uid), {
    'state.vehicle': event.target.value,
  });
}

function share() {
  if (!currentVehicleId.value) return;
  const id = prompt('共有相手のIDを入力してください');
  if (id) {
    updateDoc(doc(db, 'vehicles', currentVehicleId.value).withConverter(vehicleConverter), {
      'permissions.read': arrayUnion(id),
      'permissions.write': arrayUnion(id),
    });
  }
}

const db = getFirestore();
const trips: Ref<TripIdentified[]> = ref([]);
const newTripEnabled = ref(false);
const calculatedTrips: Ref<TripCalculated[]> = computed(() => {
  const [first, ...remains] = trips.value.sort(sortByTimestamp);
  if (!first) return [];
  return remains.reduce(([acc, odo]: [TripCalculated[], number], trip: TripIdentified): [TripCalculated[], number] => {
    acc.push({ ...trip, trip: trip.odo - odo });
    return [acc, trip.odo];
  }, [[{ ...first, trip: 0 }], first.odo])[0];
});
const classSummaries = computed(() => calculatedTrips.value.filter(({ timestamp }) => {
  return timestamp.toDate().getFullYear() === currentYear.value;
}).reduce((acc, { class: c, trip }) => {
  if (!(c in acc)) acc[c] = 0;
  if (trip !== undefined) acc[c] += trip;
  return acc;
}, {}));
const sum = computed(() => {
  const last = [...calculatedTrips.value].reverse().find(({ timestamp }) => timestamp.toDate().getFullYear() === currentYear.value);
  let first = [...calculatedTrips.value].reverse().find(({ timestamp }) => timestamp.toDate().getFullYear() === currentYear.value - 1);
  if (!first) first = calculatedTrips.value.find(({ timestamp }) => timestamp.toDate().getFullYear() === currentYear.value);
  if (!first || !last) return 0;
  return last.odo - first.odo;
});

let unsubUser: Unsubscribe;
let unsubVehicles: Unsubscribe;
watch(currentUser, (user, oldUser, invalidate) => {
  if (oldUser) {
    unsubUser();
    unsubVehicles();
    vehicles.value = [];
  }
  unsubUser = onSnapshot(doc(db, 'users', user.uid).withConverter(userConverter), async (snapshot) => {
    if (!snapshot.exists()) {
      const { data: oldTrips } = (await getDoc(doc(db, 'trips', user.uid).withConverter(tripsConverter))).data() || { data: [] };
      const classes = Array.from(oldTrips.reduce((acc, { class: cls }) => {
        return acc.add(cls);
      }, new Set<string>()));
      const name = prompt('車の名称を入力してください');
      const batch1 = writeBatch(db);
      const newVehicle = doc(collection(db, 'vehicles')).withConverter(vehicleConverter);
      await batch1
        .set(newVehicle, {
          classes,
          name,
          permissions: {
            read: [currentUser.value.uid],
            write: [currentUser.value.uid],
          },
        })
        .set(doc(db, 'users', user.uid).withConverter(userConverter), {
          state: { vehicle: newVehicle.id },
        })
        .commit();
      const batch2 = writeBatch(db);
      oldTrips.forEach((trip) => {
        batch2.set(doc(collection(db, 'vehicles', newVehicle.id, 'trips')).withConverter(tripConverter), trip);
      });
      batch2.commit();
      return;
    }
    currentVehicleId.value = snapshot.data().state.vehicle;
  });
  unsubVehicles = onSnapshot(query(collection(db, 'vehicles'), where('permissions.read', 'array-contains', user.uid)).withConverter(vehicleConverter), (snapshot) => {
    snapshot.docChanges().forEach(({ doc, type }) => {
      if (type === 'added') {
        vehicles.value.push({ ...doc.data(), id: doc.id });
      } else {
        const i = vehicles.value.findIndex(({ id }) => doc.id === id);
        if (type === 'modified') {
          vehicles.value.splice(i, 1, { ...doc.data(), id: doc.id });
        } else {
          vehicles.value.splice(i, 1);
        }
      }
    });
  });
  invalidate(unsubUser);
  invalidate(unsubVehicles);
}, {
  immediate: true,
});

let unsubVehicle: Unsubscribe;
let unsubTrips: Unsubscribe;
watch(currentVehicleId, (vehicleId, oldVehicleId, invalidate) => {
  if (oldVehicleId) {
    unsubVehicle();
    unsubTrips();
    trips.value = [];
  }
  if (!vehicleId) return;
  unsubVehicle = onSnapshot(doc(db, 'vehicles', vehicleId).withConverter(vehicleConverter), (snapshot) => {
    vehicleClasses.value = snapshot.data()?.classes || [];
  });
  unsubTrips = onSnapshot(collection(db, 'vehicles', vehicleId, 'trips').withConverter(tripConverter), (snapshot) => {
    snapshot.docChanges().forEach(({ type, doc }) => {
      if (type === 'added')
        trips.value.push({ ...doc.data(), id: doc.id });
      else {
        const i = trips.value.findIndex(({ id }) => id === doc.id);
        if (type === 'modified')
          trips.value.splice(i, 1, { ...doc.data(), id: doc.id });
        else
          trips.value.splice(i, 1);
      }
    });
  });
  invalidate(unsubVehicle);
  invalidate(unsubTrips);
}, {
  immediate:true,
});

// 一覧は新しい順に表示する（trip の差分計算は古い順のまま）
const displayTrips = computed(() => [...calculatedTrips.value].reverse());

const lastODO = computed(() => {
  const last = trips.value.at(-1);
  if (!last) return 0;
  return last.odo;
});

// 分類ごとに色を割り当て、業務用と私用を一目で見分けられるようにする
const classPalette = [
  'bg-blue-100 text-blue-800',
  'bg-amber-100 text-amber-800',
  'bg-emerald-100 text-emerald-800',
  'bg-rose-100 text-rose-800',
  'bg-violet-100 text-violet-800',
  'bg-cyan-100 text-cyan-800',
];
function classStyle(cls: string) {
  const i = vehicleClasses.value.indexOf(cls);
  return classPalette[(i < 0 ? 0 : i) % classPalette.length];
}

function formatDate(timestamp) {
  const d = timestamp.toDate();
  return `${d.getFullYear()}年${d.getMonth() + 1}月${d.getDate()}日 ${d.getHours().toString().padStart(2, '0')}:${d.getMinutes().toString().padStart(2,'0')}`;
}

function sortByTimestamp({ timestamp: t1 }, { timestamp: t2 }) {
  return t1 - t2;
}

function createTrip(trip: Trip) {
  const prevTrip = [...calculatedTrips.value].reverse().find(({ timestamp }) => trip.timestamp.seconds > timestamp.seconds || trip.timestamp.seconds === timestamp.seconds && trip.timestamp.nanoseconds > timestamp.nanoseconds);
  const nextTrip = calculatedTrips.value.find(({ timestamp }) => trip.timestamp.seconds < timestamp.seconds || trip.timestamp.seconds === timestamp.seconds && trip.timestamp.nanoseconds < timestamp.nanoseconds);
  if (prevTrip && trip.odo <= prevTrip.odo) return;
  if (nextTrip && trip.odo >= nextTrip.odo) return;
  if (!currentVehicleId.value) return;
  addDoc(collection(db, 'vehicles', currentVehicleId.value, 'trips').withConverter(tripConverter), trip);
  newTripEnabled.value = false;
}

function formatNumber(number) {
  return number.toFixed(6).replace(/\.?0*$/, '');
}
</script>
